#%RAML 0.8
---
title: tenderbit | API
baseUri: http://localhost:5400/api/{version}
version: v1

/:
    get:
        description: Retrives the status of the api
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "success": true,
                                "message": "API /api/v1"
                            }